version: "3.4"

services:
  dashboard:
    image: "registry:2"
    restart: always
    ports:
      - 5000:5000
    volumes:
      - "./data:/var/lib/registry:rw"
      - "/etc/hosts:/etc/hosts:ro"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M
